### ISSUE TITLE
How to encrypt/verify custom data ?

### ISSUE THREAD

**Issue by kosten** [RustCrypto/SSH#14]
Hello everyone!

Could someone tell me, how can I encrypt/verify my custom data via this lib ?

For example:

1. Client is sending a phone number to the server
2. Server is generating sms code and send it to the Client phone
3. Server is generating a token with combination user phone and sms code, and send it to the Client
4. Client is writing a form with a received sms code and send it to the server with phone number and token
5. Server is validating all received data and make a decision for login or not

Thanks!

**Comment by tarcieri** [comment]
The only crate we have at present, `ssh-key`, implements support for SSH keys, which are for digital signatures. Digital signatures cannot be used for encryption by definition.

To the extent it supports encryption at all, it's for encrypting the keys according to SSH conventions, and is not suitable for general purpose encryption. Otherwise, there is no encryption support at all.
