### ISSUE TITLE
ssh_key::Signature doesn't round-trip through Signature trait

### ISSUE THREAD

**Issue by programmerjake** [RustCrypto/SSH#5]
Afaict the `Signature::from_bytes` method expects a algorithm type string as a prefix, but `Signature::as_bytes` doesn't return the algorithm type string as a prefix.

**Comment by tarcieri** [comment]
I've opened a PR for a prospective `signature` v2.0 which separates a signature type from its serialization:

https://github.com/RustCrypto/traits/pull/1141

Rather than fix this issue for the `signature ` v1.0 API, I think it would be best to hold off on changes until the new `signature` API is available, where this issue will effectively be automatically addressed by the new API.

**Comment by tarcieri** [comment]
This should be addressed by #55, namely the changes here:

https://github.com/RustCrypto/SSH/pull/55/files#diff-a7d9c3005184f746fc7019de8c392d8edda5186a4c0e5e07ced7d152b0bc75d9
